name: Build Debian Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/samplescript
          echo -e "echo sample" > .debpkg/usr/bin/samplescript
          chmod +x .debpkg/usr/bin/samplescript
          echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v3
        with:
          package: samplescript
          package_root: .debpkg
          maintainer: your_name
          # version: ${{ github.ref }} # refs/tags/v*.*.*
          version: 1.0
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'this is sample package.'
          homepage: 'https://github.com/mikebrady/dacquery'
